#!/bin/bash
#
# This script creates x86_64-compatible package for 32-bit only apps, such as wine.
if [ -z "${MKPKG_DIR}" ]; then
   echo "The script starts mkpkg -64 [package]"
   exit
fi

mpkg_cache_dir="/var/mpkg/cache"

# Load global configuration
. /etc/mkpkg.conf

if [ -f "${MKPKG_DIR}/mkpkg_shared_functions" ]; then
   . "${MKPKG_DIR}/mkpkg_shared_functions"
else
   echo "Error loading shared functions block ${MKPKG_DIR}/mkpkg_shared_functions"
   exit 1
fi

PKGLIST="$@"

make_pkg64() {
  set -e
  local pkg_file=$1
  if ! [ -f "${pkg_file}" ]; then
     show_message FILE_NOT_FOUND "${pkg_file}"
     exit 1
  fi
  PKG_FULLPATH="$(readlink -f ${pkg_file})"
  PKGNAME=$(basename "${PKG_FULLPATH}")

  # Create working directory
  wd=${bt_working_dir}.${USER}/32to64/${PKGNAME}
  orig_dir=${wd}/orig
  dest_dir=${wd}/dest
  rm -rf "${wd}"
  mkdir -p "${orig_dir}"
  mkdir -p "${dest_dir}"
  ( cd "${orig_dir}" ; tar -xf "${PKG_FULLPATH}" )
  # Copy metadata
  mkdir ${dest_dir}/install
  cp -r ${orig_dir}/* ${dest_dir}
  pkginfo="$(mkpkg_xml_parser ${dest_dir}/install/data.xml -p)"
  tpkgname=`echo ${pkginfo} | cut -d ' ' -f 1`
  tpkgver=`echo ${pkginfo} | cut -d ' ' -f 2`
  tpkgbuild=`echo ${pkginfo} | cut -d ' ' -f 4`
  tpkgarch=`echo ${pkginfo} | cut -d ' ' -f 3`
  if [ ${tpkgarch} != "i686" ]; then
     show_message INCORRECT_ARCH_PACKAGE "${tpkgarch}" "${PKGNAME}"
     exit
  fi

  show_message REPLACING_TAGS
  replace_tags

  show_message MODIFYING_METADATA
  modify_meta

  show_message MODIFYING_DEPS
  modify_deps

  show_message PACKING_BACK
  # Package it and move to packages directory
  ( cd ${dest_dir} ; buildpkg ${package_out_dir}/ )
  if [ "${NOT_CLEAR_SOURCE}" != "1" ]; then
     show_message DELETE_TEMPORARY_FILES
     rm -fr "${wd}"
  fi
  set +e
}

check_deps() {
  IP="api.agilialinux.ru"
  show_message CHECKING_PACKAGE_DEPS "«${newdep_name}»"
  local dep_ver=$(echo ${newdep_tail} | sed 's/^[>=<]*//g')
  local find_package=""
  local name_four=`echo "${newdep_name}" | sed 's/\(.\{1,4\}\).*/\1/'`
  if [ "${name_four}" = "wine" ]; then
      echo -e "\e[31mAdd because the first four characters wine\e[0m"
      return 1
  fi
  find_package_directory find_package ${package_out_dir} "i686 noarch"
  if [ -z "${find_package}" ]; then
     find_package_directory find_package ${mpkg_cache_dir} "i686 noarch"
     if [ -z "${find_package}" ]; then
        ping_res=1
        /bin/ping ${IP} -c 2 > /dev/null 2>&1 && ping_res=0
        if [ ${ping_res} -ne 0 ]; then
           show_message UNABLE_CONNECT_SERVER "${IP}"
           exit 1
        fi
        if [ -z "${dep_ver}" ]; then
           wget --no-check-certificate -P ${package_out_dir}/deps "http://${IP}/pkg/${newdep_name}/i686"
        else
           wget --no-check-certificate -P ${package_out_dir}/deps "http://${IP}/pkg/${newdep_name}/i686/${dep_ver}"
        fi
        find_package_directory find_package ${package_out_dir}/deps "i686 noarch"
     else
        show_message FOUND_PACKAGE_DIR "${find_package}" "${package_out_dir}"
     fi
  else
     show_message FOUND_PACKAGE_DIR "${find_package}" "${package_out_dir}"
  fi
  if [ -z ${find_package} ]; then
     show_message COULD_NOT_FIND_PACKAGE "«${newdep_name}»"
     #Когда баги с зависимостями исправятся нужно убрать lib
     local name_three=`echo "${newdep_name}" | sed 's/\(.\{1,3\}\).*/\1/'`
     if [ "${name_three}" != "lib" ]; then
        exit 1
     else
       echo -e "\e[31mAdd because the first three characters lib\e[0m"
       return 0
     fi
  fi
  local find_package="$(readlink -f ${find_package})"
  local deps_dir="${wd}/deps/${newdep_name}-${dep_ver}"
  mkdir -p "${deps_dir}"
  if ! [ -d "${deps_dir}" ]; then
     show_message FAILED_TO_CREATE_DIR "${deps_dir}"
     exit 1
  fi
  cd "${deps_dir}"
  tar -xf "${find_package}"
  local find_dep_lib=1
  for f in $(find . -name '*.so') $(find . -name '*.so.*') ; do
      local dir_name=$(dirname $f)
      check_dir_whitelist ${dir_name} || continue
      find_dep_lib=0
      break
  done
  return ${find_dep_lib}
}

modify_deps() {
  deps="$(mkpkg_xml_parser ${dest_dir}/install/data.xml -d)"
  local depstring="-Z "
  for d in ${deps} ; do
      newdep_name="$(echo $d | sed 's/[>=<!].*//g')"
      newdep_tail="$(echo $d | sed 's/^[^>=<!]*//g')"
      set +e
      check_deps
      local res_check_deps=$?
      if [ ${res_check_deps} = 2 ]; then
         show_message NOT_ADDED_PACKAGE_DEPS "«${newdep_name}»"
         continue
      fi
      set -e
      if [ ${res_check_deps} = 1 ]; then
         local depstring+="-d ${newdep_name}${newdep_tail} "
      else
         local depstring+="-d ${newdep_name}32${newdep_tail} "
      fi
  done
  mpkg-setmeta "${dest_dir}" ${depstring}
  return 0
}

modify_meta() {
  mpkg-setmeta ${dest_dir} --arch=x86_64

  return 0
}

replace_tags() {
  echo "DEST: ${dest_dir}"
  # Modify metadata
  # Tags
  pkgtags="$(mkpkg_xml_parser ${dest_dir}/install/data.xml -t)"
  taglist=
  found=0
  tagstring="--cleartags "

  for tag in ${pkgtags}; do
      taglist+=" ${tag} "
  done
  taglist+=" x86 "

  for tg in ${taglist}; do
      tagstring+="--add-tag=${tg} "
  done
  mpkg-setmeta ${dest_dir} ${tagstring}
  return 0
}

# Run stuff
for i in ${PKGLIST} ; do 
    make_pkg64 $i
done
