#!/bin/bash
# This script converts i686 package to x86_64 compat32 package by stripping unneeded files


# Load global configuration
. /etc/mkpkg.conf

PKGLIST="$@"

make_compat32() {
	set -e
	PKG_FULLPATH="$(readlink -f $1)"
	PKGNAME=$(basename "$PKG_FULLPATH")

	# Create working directory
	wd=${bt_working_dir}.${USER}/32to64/$PKGNAME
	orig_dir=${wd}/orig
	dest_dir=${wd}/dest
	rm -rf $wd
	mkdir -p $orig_dir
	mkdir -p $dest_dir
	( cd $orig_dir ; tar -xf "$PKG_FULLPATH" )

	# Copy metadata
	mkdir ${dest_dir}/install
	cp ${orig_dir}/install/data.xml ${dest_dir}/install/data.xml

	# Copy libs
	( cd ${orig_dir}
		for i in $(find . -name '*.so') $(find . -name '*.so.*') ; do
			echo "Moving lib $i"
			install -Dm0755 $i ${dest_dir}/$i
		done
	)

	# Copy ABUILD
	pkginfo="$(python /usr/share/mpkg/mkpkg/mkpkg_xml_parser.py $dest_dir/install/data.xml -p)"
	pkgname=$(echo $pkginfo | sed 's/\s.*//g')
	orig_abuild=$(basename ${orig_dir}/usr/src/BuildTrees/${pkgname}-*.build_tree.tar.xz)
	dest_abuild=$(echo ${orig_abuild} | sed s/${pkgname}/${pkgname}32/g)
	install -Dm0644 ${orig_dir}/usr/src/BuildTrees/${orig_abuild} ${dest_dir}/usr/src/BuildTrees/${dest_abuild}

	# Do data.xml magic
	echo "Replacing tags"
	replace_tags ${dest_dir}

	echo "Modifying meta"
	modify_meta ${dest_dir}

	echo "Modifying deps"
	modify_deps ${dest_dir}

	echo "Packing back"
	# Package it and move to packages directory
	( cd ${dest_dir} ; buildpkg ${package_out_dir}/ )
	set +e
}

replace_tags() {
	dest_dir="$1"
	# Modify metadata
	# Tags
	pkgtags="$(python /usr/share/mpkg/mkpkg/mkpkg_xml_parser.py $dest_dir/install/data.xml -t)"
	taglist=
	found=0
	tagstring="--cleartags "

	for tag in $pkgtags; do
		result="$(echo $tag | grep '-' || true)"
		if [ -z "${result}" -a "$found" == 0 ]; then
			taglist+=" compat32 "
			found=1
		else
			taglist+=" ${tag} "
			taglist+=" x86 "
		fi
	done
	for tg in ${taglist}; do
		tagstring+="--add-tag=$tg "
	done
	mpkg-setmeta ${dest_dir} ${tagstring}
	return 0
}

modify_meta() {
	dest_dir="$1"
	pkginfo="$(python /usr/share/mpkg/mkpkg/mkpkg_xml_parser.py $dest_dir/install/data.xml -p)"
	pkgname=$(echo $pkginfo | sed 's/\s.*//g')

	mpkg-setmeta ${dest_dir} --arch=x86_64 --name=${pkgname}32 

	return 0
}

modify_deps() {
	dest_dir="$1"
	deps="$(python /usr/share/mpkg/mkpkg/mkpkg_xml_parser.py $dest_dir/install/data.xml -d)"
	depstring="-Z "
	for d in $deps ; do
		newdep_name="$(echo $d | sed 's/[>=<!].*//g')"
		newdep_tail="$(echo $d | sed 's/^[^>=<!]*//g')"

		depstring+="-d ${newdep_name}32${newdep_tail} "
	done
	mpkg-setmeta ${dest_dir} ${depstring}

	return 0
}


# Run stuff
for i in ${PKGLIST} ; do 
	make_compat32 $i
done

